# definición de atajos para no escribir los comandos

# construye las imágenes del docker-compose
build:
\tdocker compose build

# levanta todos los contenedores
up:
\tdocker compose up -d

#apaga y elimina los contenedores, ayuda a limpiar y detener todo
down:
\tdocker compose down

#muestra los logs combinados de todos los servicios
logs:
\tdocker compose logs -f

#lista el estado actual de todos los contenedores
ps:
\tdocker compose ps

